### ISSUE TITLE
Class 'StripeCheckoutCustom' not found

### ISSUE THREAD

**Issue by cicsolutions** [ruskid/yii2-stripe#1]
Hello, and thank you for creating this Stripe wrapper.  

I've followed your installation instructions, however I'm receiving a class not found error when trying to echo forms.

I think we need to have a "use" namespace statement at the top of our view, so we can reference your stripe class.  I'm not very familiar with how components identified in the config file are referenced, but I think we need a way to say where the StripeCheckoutCustom class is to be found from our view files.

I tried placing the following at the top of my view file, but it did not seem to work:
use ruskid\stripe;

Any suggestions you can offer are greatly appreciated!

**Comment by ruskid** [comment]
Yep, use ruskid\stripe\StripeCheckoutCustom;
glad you use it ;) feedback is appreciated
