### ISSUE TITLE
CSRF

### ISSUE THREAD

**Issue by xavsio4** [ruskid/yii2-stripe#2]
Hello, I had to alter your function "generateStripeForm()" in stripeCheckout.php   in order to be able to catch the form in my controller Action. I reckon it is not very elegant but it worked. Otherwise i get this Bad Request (#400): Unable to verify your data submission because of csrf check.

```
private function generateStripeForm() {

        $csrf = '<input type="hidden" name="'.Yii::$app->request->csrfParam.'" value="'.Yii::$app->request->csrfToken.'" />';
        return Html::tag('form', $csrf.$this->generateScriptTag(), array(
                    'action' => $this->action,
                    'method' => 'POST',
        ));
    }

```

**Comment by ruskid** [comment]
fixed. thx!
