### ISSUE TITLE
tag a release before adding any features?

### ISSUE THREAD

**Issue by PrplHaz4** [ruskid/yii2-stripe#5]
Think you can tag a release of this before adding any more features?  Seems like it works pretty well right now, and we should be able to lock our installs to this version.

**Comment by ruskid** [comment]
Sure, gonna finish Jquery Payment Validation. 
and release tomorrow or the day after tomorrow.
Thx

**Comment by PrplHaz4** [comment]
Sounds good - definitely had problems with the single field for month/year, but didn't have time to fiddle with it...lots of discussion about that in the jquery.payment repo, but don't know the best way to make it work with this library.  Everything else worked and was super quick to integrate...Thanks!!

**Comment by ruskid** [comment]
Hi. hmm. don't know about the problems, jquery payment working good for me.
just finished and created first release.

**Comment by PrplHaz4** [comment]
@ruskid have you tested with month/year combined, and individually?  I seem to be getting a js error when using separate month and year inputs:
`Uncaught TypeError: Cannot read property 'replace' of undefined` (in $.payment.cardExpiryVal)

Also, when I try to replace it with a combined month/year input, a two digit year returns:
`Your card's expiration year is invalid.`

(this is with v1.0)

**Comment by ruskid** [comment]
Ah yep. on combined input you should split the value and set to the hidden separate month and year inputs. So it could be posted to stripe. Something like this.

``` javascript
function splitMonthAndYear(monthYear) {
    var res = monthYear.split(" / ", 2);
    $("#cc-exp-month").val(res[0]);
    $("#cc-exp-year").val(res[1]);
}
```

I am busy this week, this weekend I can take a look on this.

**Comment by ruskid** [comment]
Finally got time to fix the issue. Thanks for the feedback
