### ISSUE TITLE
composer failing to install

### ISSUE THREAD

**Issue by davidjeddy** [ruskid/yii2-stripe#7]
Command:

Results:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ruskid/yii2-stripe dev-master -> satisfiable by ruskid/yii2-stripe[dev-master].
    - ruskid/yii2-stripe dev-master requires bower-asset/jquery.payment 1.2.2 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.`

**Comment by davidjeddy** [comment]
Nvmd, forgot to run `composer global require "fxp/composer-asset-plugin:~1.1"` first.

**Comment by Clever91** [comment]
or php composer.phar global require "fxp/composer-asset-plugin:~1.1" first
