### ISSUE TITLE
Feature Add: Keep other default values when one value is overwritten.

### ISSUE THREAD

**Issue by davidjeddy** [ruskid/yii2-stripe#9]
Currently overwriting one form method causes all defualt options to be lost. IE:

```
        echo $form->numberInput([
            'placeholder' => 'Card Number *',
            'class'       => 'form-control'
        ]);
```

will prevent the 'required' option from being set.

Recommendation:
In the form option methods over write only those key/ value pairs and retain default values for others

```
        echo $form->numberInput([
            'placeholder' => 'Card Number *',
            'class'       => 'form-control'
        ]);
```

would end up being 

```
       echo $form->numberInput([
            'id'            => self::NUMBER_ID,
            'class'         => 'form-control',
            'autocomplete'  => self::AUTO_CC_ATTR,
            'placeholder'   => 'Card Number*',
            'required'      => true,
            'type'          => 'tel',
            'size'          => 20
        ]);
```

after the method outputs the fields options.

**Comment by ruskid** [comment]
yep I know. array merge should work. Can you take a look in a free time?

**Comment by davidjeddy** [comment]
I can do that. I'll fork it and submit a pull request for the feature add.

**Comment by davidjeddy** [comment]
PR created https://github.com/ruskid/yii2-stripe/pull/10

**Comment by ruskid** [comment]
Fixed. thanks
